### PR TITLE
added support for SYNC counter in SimpleSyncLayer

### LINKED ISSUE #348: SimpleSyncLayer does not handle overflow sync counter
Setting the overflow param to any value between 0 and 240 should result into a counter value inside the sync frame. The external sync (bcm_sync) is doing it correctly but the internal sync (SimpleSyncLayer) is not.

relevant code section: https://github.com/ros-industrial/ros_canopen/blob/melodic-devel/canopen_master/src/master_plugin.cpp#L53

### PR DESCRIPTION
**Pull request by mathias-luedtke**
fixes #348 

@benmaidel: please test

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Not sure, if the counter should get reset at some point.

**Review by benmaidel — APPROVED** [review]
Successfully tested with cob base. Sync counter is counting if enabled.

**Comment by mathias-luedtke** [comment]
@benmaidel: I guess you need this for kinetic as well, don't you?

**Comment by benmaidel** [comment]
> @benmaidel: I guess you need this for kinetic as well, don't you?

right, for now I've cherry picked the commit into kinetic-devel. Works fine! Now I've also seen your backport to kinetic https://github.com/ros-industrial/ros_canopen/pull/351 :+1: 
@ipa-mdl thx for support

**Pull request merged**
