### PR TITLE
[WIP] update and unify Readme files

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by Timple** [comment]
The readme table says 'supported' for 'jade'. The description below says 'unsupported (EOL)'.

**Comment by mathias-luedtke** [comment]
> The readme table says 'supported' for 'jade'. The description below says 'unsupported (EOL)'.

Yes, that's one of the issues.
I think I will take only some of these changes in.

**Review by mathias-luedtke — CHANGES_REQUESTED** [review]
This approach does not work for me.
I will try to come up with an alternative.

**Comment by ipa-nhg** [comment]
@ipa-mdl you were too fast... please check again and see https://github.com/ros-industrial/ros_industrial_issues/issues/55#issuecomment-408073043

**Comment by mathias-luedtke** [comment]
I will close this now, it is outdated. Most links to the buildfarm do not work anymore.

**Pull request closed without merging**
