### PR TITLE
Address inconsistent override warning

### PR DESCRIPTION
**Pull request by wxmerkt**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Which warning did you get? In CI I cannot see them.
Why only those 5 lines? I guess we could fix that in all files..

**Comment by wxmerkt** [comment]
With clang we get `-Winconsistent-missing-overrides`. These were the only ones that were triggered. I also added a commit to address the deprecation of filter_chain.h in Noetic while keeping Melodic compatibility. I no longer see any warnings building this repository

**Review by mathias-luedtke — APPROVED** [review]

**Comment by wxmerkt** [comment]
@ipa-hsd friendly ping - is this good to merge?

**Comment by hsd-dev** [comment]
Sorry I think it got lost in my emails.

**Pull request merged**
