### PR TITLE
Jade fixes and single-mode check

### PR DESCRIPTION
**Pull request by mathias-luedtke**
contains #198

### CODE REVIEW

**Comment by mistoll** [comment]
Tested it on our kinetic system. No Problems, so far.

**Comment by mathias-luedtke** [comment]
If it works with kinetic, jade should be fine as well.
Not sure if we need a specific kinetic branch.

**Comment by mistoll** [comment]
I dont't have a jade system, so can't say anything about that.

IMO you should keep it simple and only create a kinetic branch, if you have to.

**Comment by floweisshardt** [comment]
kinectic is the official LTS of ROS, so it makes sense for me to have a kinectic branch (and probably skip support for the jade branch)

**Comment by mathias-luedtke** [comment]
I will keep the `jade-devel` as long as it works for jade and kinetic and will branch as soon as a breaking change occurs.

At some point `jade-devel` will become the master branch.
TODO: add hint on compatibility to readme

**Pull request merged**
