### PR TITLE
Replacing FastDelegate with std::function and std::bind.

### PR DESCRIPTION
**Pull request by JWhitleyWork**
FastDelegate is not optimized for usability with C++11/14 features. In addition, the std library functions are much more portable, if possibly slightly slower.

I attempted to maintain API compatibility but the function signatures are so different between FastDelegate and std::function/std::bind that I ended up creating a utility function with FastDelegate's signature. I thought about inheriting from std::function to replace the typedefs but I couldn't think of a way to do it and have a constructor with the same signature of FastDelegate without knowing/reimplementing some of the std::function internals. Please let me know if you can think of a way that will maintain API compatibility.

This is an alternative to PR #318.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@ipa-mdl - I found a way to not break API! Hooray! It seems a little hack-y, though. Can you review?

**Comment by mathias-luedtke** [comment]
Overall: :+1: 

Two comments/ideas:
* I'd like to allow passing just `std::function`, so we could just add a *DelegateFunc type for use in interfaces
* Is it possible to write a template that provides the *Delegate wrapper?

The first one should be easy to do.
The second should be possible as well, if not a macro could be an alternative.
I will try to come up with something.

What do you think?

**Comment by JWhitleyWork** [comment]
@ipa-mdl - Since the *Delegate classes inherit from `std::function`, they have all of it's default constructors (including the copy and move constructors) so you can do something like:

    FrameDelegate fd = std::bind(...)

or

    FrameDelegate fd(std::bind(...))

As well as the FastDelegate-like forms for which I created new constructors. I think this covers your first requirement. I'm not sure I understand your second requirement. Could you elaborate a little bit more or provide a use case?

**Comment by mathias-luedtke** [comment]
> Since the *Delegate classes inherit from `std::function`, they have all of it's default constructors (including the copy and move constructors)

This should not be the case (?).
But you can pass *Delegate instances to the `std::function` constructors 

> so you can do something like:

Yep, you are right, this should work :)
I thought (but did not write..) that the *Delegate classes could get deprecated at some point.

>  Could you elaborate a little bit more or provide a use case?

I'd like to have something like this:

```c++
using FrameFunc = std::function(void(const Frame&)>)
using FrameDelegate = DelegateHelper<FrameFunc>;
```

or

```c++
using FrameDelegate = DelegateHelper<void(const Frame&)>;
using FrameFunc = FrameDelegate::func_type;
```

I tried to implement `DelegateHelper` yesterday, but i did not yet find a solution that works for an arbitrary number( we need 0-2 )of arguments / placeholders..

**Comment by JWhitleyWork** [comment]
So, just to clarify, you want FrameDelegate to essentially be a specialization of `std::function` that specifically uses the function signature `void(const Frame&)`, correct? What are you imagining the constructor for a FrameDelegate would look like? I did this before I implemented the "non-api-breaking" version of this but it required a call to `std::bind` in order to create a delegate for the specific function that you wanted attached to the function. Below are a few options of how this could look, both with and without using `std::bind`. Let me know which one you want and I'll get that in.

1.

    FrameDelegate foo1(std::bind(&CommInterfaceChild::func, &instance, std::placeholders::_1);
    TimerDelegate foo2(std::bind(&TimerChild::func, &instance);
    ReadDelegate foo3(std::bind(&ObjectStorageChild::func, &instance, std::placeholders::_1, std::placeholders::_2);

2.

    FrameDelegate foo1 = DelegateHelper<FrameDelegate>(&CommInterfaceChild::func, &instance);
    TimerDelegate foo2 = DelegateHelper<TimerDelegate>(&TimerChild::func, &instance);
    ReadDelegate foo3 = DelegateHelper<ReadDelegate>(&ObjectStorageChild::func, &instance);

3.

    using FrameDelegate = DelegateHelper<void(const Frame&)>;
    using TimerDelegate = DelegateHelper<bool(void)>;
    using ReadDelegate = DelegateHelper<void(const ObjectDict::Entry&, String&)>;

    FrameDelegate foo1(&CommInterfaceChild::func, &instance);
    TimerDelegate foo2(&TimerChild::func, &instance);
    ReadDelegate foo3(&ObjectStorageChild::func, &instance);

FYI - The current implementation is similar to option 3 but the order of the arguments is reversed.

Also, do you care about breaking API? If not, I'll implement this and change all references to it as well.

**Comment by mathias-luedtke** [comment]
I'd like to make the `std:function` interface the default, which will be used together with `std::bind` or lambda functions (option 1).
For backwards compatibility, it would be nice to have an API-compatible *Delegate type available (option 3), which could be marked as deprecated (later).

**Comment by mathias-luedtke** [comment]
@JWhitleyAStuff: I am preparing the *Func patch right now and open a PR to your fork soon.

**Comment by mathias-luedtke** [comment]
I have now figured out how to implement `DelegateHelper`:

```c++
template <typename T> class DelegateHelper : public T {
public:
    template <typename Object, typename Instance, typename ...Args>
    DelegateHelper(Object &&o, typename T::result_type (Instance::*member)(Args... args)) :
        T([&o, fn=std::mem_fn(member)](Args... args) -> typename T::result_type { return fn(o, args...); })
    {
    }
    template <typename Callable>
    DelegateHelper(Callable &&c) : T(c)
    {
    }
};

using StateFunc = std::function<void(const State&)>;
using StateDelegate = DelegateHelper<StateFunc>;
```

Perhaps `std::forward`  could be added in some places ^^

**Comment by JWhitleyWork** [comment]
Do you want me to add this to this PR?

**Comment by mathias-luedtke** [comment]
> Do you want me to add this to this PR?

Yes, please try it.
It would be good as well to have a small test that tests the Delegate to work as before.

I will try to provide a benchmark.

**Comment by JWhitleyWork** [comment]
@ipa-mdl - In the suggested function above, you're using an initialized lamda capture. This requires C++14. Should we reorganize for C++11 or should we add -std=C++14 to the CMakeLists.txt?

**Comment by JWhitleyWork** [comment]
I have added the code and made the necessary changes. So that there is easier access to the DelegateHelper without all of SocketCANInterface, I have moved it to socketcan_interface/helpers.h. Please let me know if this is OK. You may have to develop the test as I'm not as familiar with the concepts behind how the Delegates were used.

**Comment by mathias-luedtke** [comment]
> This requires C++14. Should we reorganize for C++11 or should we add -std=C++14 to the CMakeLists.txt?

No, C++14 is the default for Ubuntu 18.04 and melodic.
I was not able to do this in C++11, but we can reorganize if possible.

**Comment by JWhitleyWork** [comment]
If this is only targeting Melodic and above (and eventually ROS2), then I'm fine with just leaving it. My goal behind this was to get the whole repo to a ROS2-ready state anyway. Everything compiles and all tests succeed (minus the one that I hope you'll write for Delegates). If you're happy with the changes, I'm good for merge minus that last test.

FYI - I'm working on the ROS2 version here: https://github.com/JWhitleyAStuff/ros_canopen/tree/crystal-devel

**Comment by mathias-luedtke** [comment]
I have now added some API tests.
Next step: simple benchmarking tool and a CANopen hardware test.

> FYI - I'm working on the ROS2 version here: https://github.com/JWhitleyAStuff/ros_canopen/tree/crystal-devel

Great!
Not sure if we should split the repositories to simplify the migration (#103).

**Comment by mathias-luedtke** [comment]
I have run some benchmark and the new version is around 30% slower, but still at very high level (~10Mhz if I recall it correctly).
Combined with the dispatcher and the actual CAN device, this is not noticeable anymore.

However, somehow my tests crash in Docker (or at least don't output results).
I am still investigating..

**Comment by JWhitleyWork** [comment]
@ipa-mdl - Since we were already working on socketcan_interface, I went ahead and replaced all typedefs with using aliases. They're functionally identical except that aliases can be used in templated functions and typedefs can't. Figured it wouldn't hurt and it's helpful for the ROS2 transition anyway.

**Comment by JWhitleyWork** [comment]
@ipa-mdl Ping

**Comment by mathias-luedtke** [comment]
Sry, it took me time to hunt the segmentation fault.
https://github.com/JWhitleyAStuff/ros_canopen/pull/5 should fix it.
After the merge  the branch needs to be rebased (proper commits without merge) and then we need to test it with real HW.

**Comment by mathias-luedtke** [comment]
@JWhitleyAStuff: Do you have to rebase the branch properly or should I got ahead a push to you branch?
The tests can be fixed by dropping ef420b797d42e0e8737ad795f68919fc844f43f2 during the rebase.

**Comment by JWhitleyWork** [comment]
@ipa-mdl Just rebased on `melodic-devel`.

**Comment by JWhitleyWork** [comment]
@ipa-mdl - Isn't ef420b7 necessary to run the test?

**Comment by mathias-luedtke** [comment]
> Isn't ef420b7 necessary to run the test? 

No, it was just a standalone node. I refactored it later into a test.
I have now removed this commit and deprecated the delegates (https://github.com/ipa-mdl/ros_canopen/commits/JWhitleyAStuff-maint/std_function).
I went ahed and rebased it as well: https://github.com/ipa-mdl/ros_canopen/commits/JWhitleyAStuff-maint/std_function-rebased
@JWhitleyAStuff: If this rebased version is okay for you, I would force-push it onto your branch.

I already tested the version with a CANopen manipulator and it seems to work :)
@jschleicher: It would be great, if you could give it a try as well.

**Comment by JWhitleyWork** [comment]
@ipa-mdl - Go ahead and force-push it. The benchmark looks fine.

**Review by mathias-luedtke — APPROVED** [review]
@JWhitleyAStuff: Thanks a lot for these many iterations! It is ready for merge.
I am just waiting for @jschleicher's feedback.

**Review by jschleicher — APPROVED** [review]
Works as before; no changes detected.

**Comment by mathias-luedtke** [comment]
Little glitch fixed in 9a393ae735306f077037145c70cd99df31c3223c. ROS buildfarm complained about the "deprecated" warning in the test of the backwards compatibilty. ..

**Pull request merged**
