### PR TITLE
Dashing devel

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Not everything is complete yet but this adds the majority of a port to ROS Dashing.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
First of all: Thank you very much, that was a lot of work!
It will take some time to review..

In general I would like to backport some of it (code layout, hpp, etc.) to melodic as well, otherwise the maintenance is too hard.

The commit history looks a little bit strange..

**Comment by JWhitleyWork** [comment]
Since it sat for a while, there were changes that were made to melodic-devel during development. I had to rebase on melodic-devel to pick them up. That's why the commit history is odd.

**Comment by mathias-luedtke** [comment]
>  I had to rebase on melodic-devel to pick them up. That's why the commit history is odd.

It looks like some commits are duplicated now.
This needs so get sorted out before the review.
I will see if I can find some time to do so.

**Comment by mathias-luedtke** [comment]
@JWhitleyAStuff: I actually wanted to create a PR, but Github pushed it directly.

**Comment by JWhitleyWork** [comment]
FYI - there are a few tests that are still failing. Hence the "nearly compete" port. I plan to straighten them out today.

**Comment by JWhitleyWork** [comment]
Cancelling this PR to try again with cleaner `git` history.

**Pull request closed without merging**
