### PR TITLE
Added can device recovery code

### PR DESCRIPTION
**Pull request by akashmod**
This is to solve issue 468. A ros timer is started to check the driver state after every specified duration and to reinitialize the driver for the node if the driver has recovered.

### CODE REVIEW

**Comment by BenArtes** [comment]
Summary notes for any reviewers: This covers similar ground as PR #249 (5 years old and waiting for changes) and #310 (4 years old and VERY minimal).

I think whatever happens to the socketcan_bridge auto-recovery code, the ThreadedSocketCANInterface should be merged as a (potentially) separate PR as it fixes a seemingly missing piece from ThreadedSocketCANInterface recovery code (as I ran into in issue #467).

**Comment by BenArtes** [comment]
Also, shouldn't ThreadedSocketCANInterface `virtual void recover` have a bool return type?

**Comment by akashmod** [comment]
The virtual void recover should have a bool return type yes. That needs to be corrected.

**Comment by carlesu** [comment]
Hello, Tank you very much!! This was giving me a big headache, because we actually have a device that has on/off using dead man button and had to restart the node in order to send new data. Been following #467 since then, this seems to solve the problem.

Is it possible to know approximately when could this be updated to noetic release?

Thank you again for the effort!

**Pull request closed without merging**
