### PR TITLE
Mainly fixes the controller problems when using the Elmo chain

### PR DESCRIPTION
**Pull request by thiagodefreitas**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Visual review: OK

Solves more than the controller problems:
- proper locking at interface switch
- fixed unitialized members that lead to crashes from time to time
- accept SDO responses that are larger than requested (=Elmo bug)
- reset emergency errors twice

Was tested on new base and lwa4d, but needs more tests for confirmance, in particular with cob4-2.

**Comment by floweisshardt** [comment]
visual review: OK
will wait with merging for cob4-2 test results

**Comment by ipa-nhg** [comment]
Visual Review: OK

**Comment by floweisshardt** [comment]
tested on cob4-2: FAILED

```
[ INFO] [1423495618.422571052]: Initializing XXX
[ INFO] [1423495618.423004591]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1423495618.423200208]: Current state: 2 device error: system:0 internal_error: 0 (OK)
[ INFO] [1423495618.467720944]: waitForService: Service [/arm_left/controller_manager/load_controller] has not been advertised, waiting...
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
[ERROR] [1423495620.355159752]: /u/fmw/git/care-o-bot/src/ros_canopen/canopen_master/include/canopen_master/objdict.h(343): Throw in function void canopen::ObjectStorage::Entry<T>::set(const T&) [with T = int]
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<canopen::PointerInvalid> >
std::exception::what: std::exception
[ERROR] [1423495621.359380378]: /u/fmw/git/care-o-bot/src/ros_canopen/canopen_master/src/pdo.cpp(270): Throw in function void canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<canopen::TimeoutException> >
std::exception::what: std::exception
[ERROR] [1423495622.366528185]: /u/fmw/git/care-o-bot/src/ros_canopen/canopen_master/src/pdo.cpp(270): Throw in function void canopen::PDOMapper::RPDO::sync()
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<canopen::TimeoutException> >
std::exception::what: std::exception
```

**Comment by floweisshardt** [comment]
another test on cob4-2:

```
[ INFO] [1423495947.048397226]: Initializing XXX
[ INFO] [1423495947.048828400]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1423495947.049053946]: Current state: 2 device error: system:0 internal_error: 0 (OK)
RPDOs: 3
TPDOs: 2
[ INFO] [1423495947.256193573]: waitForService: Service [/sensorring/controller_manager/load_controller] has not been advertised, waiting...
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
[ INFO] [1423495948.259491584]: waitForService: Service [/arm_left/controller_manager/load_controller] has not been advertised, waiting...
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
RPDOs: 3
TPDOs: 2
Propertly initialized module
Propertly initialized module
Propertly initialized module
[ INFO] [1423495949.266932549]: waitForService: Service [/arm_right/controller_manager/load_controller] has not been advertised, waiting...
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
[ INFO] [1423495949.527928281]: waitForService: Service [/arm_left/controller_manager/load_controller] is now available.
[ INFO] [1423495950.001031830]: joint_trajectory_controller loaded
[ INFO] [1423495950.590839623]: joint_group_position_controller loaded
[ INFO] [1423495950.624069321]: advertised as /joint_states
[ INFO] [1423495950.900753184]: joint_group_velocity_controller loaded
[ INFO] [1423495950.910660218]: Switched Controllers. From no_stop_controller_defined to joint_trajectory_controller
[ INFO] [1423495949.266932549]: waitForService: Service [/arm_right/controller_manager/load_controller] has not been advertised, waiting...
Propertly initialized module
Propertly initialized module
Propertly initialized module
Propertly initialized module
[ INFO] [1423495949.527928281]: waitForService: Service [/arm_left/controller_manager/load_controller] is now available.
[ INFO] [1423495950.001031830]: joint_trajectory_controller loaded
[ INFO] [1423495950.590839623]: joint_group_position_controller loaded
[ INFO] [1423495950.624069321]: advertised as /joint_states
[ INFO] [1423495950.900753184]: joint_group_velocity_controller loaded
[ INFO] [1423495950.910660218]: Switched Controllers. From no_stop_controller_defined to joint_trajectory_controller
```

but heard no 'click' and cannot move the arm.

**Comment by floweisshardt** [comment]
this is strange: but it worked out today without changing any code! I could successfully init and move the arm.

**Comment by floweisshardt** [comment]
tested on cob4-2: OK

**Comment by mathias-luedtke** [comment]
Was the upstart script (with old code) running before?
Maybe it is a sporadic bug..

@thiagodefreitas: "Propertly initialized module" is only listed 11 times, but should be 14 times, right?

**Comment by thiagodefreitas** [comment]
@ipa-mdl That's correct.

**Pull request merged**
