### PR TITLE
handle invalid supported drive modes object

### PR DESCRIPTION
**Pull request by mathias-luedtke**
@akosodry: please test what happens if you start the node with the wrong datatype.

### CODE REVIEW

**Comment by akosodry** [comment]
@ipa-mdl: sorry, i dont really understand what should i test?
Now the object has the following values:

```
[6502]
ParameterName=Supported drive modes
ObjectType=0x7
DataType=0x0007
LowLimit=
HighLimit=
AccessType=ro
DefaultValue=0x0000006D
PDOMapping=1
ObjFlags=0x0
```

Should i change back the DataType to DataType=0x0004 (original value)? and test what happens?

Should i edit the motor.cpp and add the new lines?

If the aforementioned was the task, then i did it (changed back the datatype and added the lines in motor.cpp). Actually, nothing new happens: i started the launch file, could initialize the driver, joint_state_controller was succesfully spawned.

**Comment by mathias-luedtke** [comment]
@akosodry: The error with the invalid `6502' was so hard to find because it did not get reported anywhere-
This PR will throw an exception in this case, because it must be an error.

> Should i change back the DataType to DataType=0x0004 (original value)? and test what happens?

Yes, exactly.
 
> Should i edit the motor.cpp and add the new lines?

Or simply checkout my branch ;)

>  Actually, nothing new happens: i started the launch file, could initialize the driver, joint_state_controller was succesfully spawned.

Hmm, this is so not was I have expected. ~~It should either crash the node or show up in the init serivce response..~~

**Comment by akosodry** [comment]
@ipa-mdl Hello Mathias! Yesterday i was in a hurry, i will test again in a 20 minutes. And i will confirm once more what is happening. 
Regarding the question [on answers.ros](https://answers.ros.org/question/294869/ros_canopen-error-after-spawning-controllers/) could you check the updates i posted (edited part of the question)?

**Comment by akosodry** [comment]
Hello! I tested again, and the same is the situation.
with DataType=0x0004 nothing new happens: i was able to launch the nodes through the robot.launch file,
then i was also able to initialize the driver.

Here is the terminal window content:

`SUMMARY

CLEAR PARAMETERS
 * /canopen_driver/

PARAMETERS
 * /canopen_driver/bus/device: can0
 * /canopen_driver/defaults/eds_file: config/eds/ASDA_A...
 * /canopen_driver/defaults/eds_pkg: motor_control_own
 * /canopen_driver/defaults/eff_from_device: 0
 * /canopen_driver/defaults/eff_to_device: rint(eff)
 * /canopen_driver/defaults/encoder_resolution: 1048576
 * /canopen_driver/defaults/motor_allocator: canopen::Motor402...
 * /canopen_driver/defaults/motor_layer/switching_state: 5
 * /canopen_driver/defaults/pos_from_device: deg2rad(obj6064)*...
 * /canopen_driver/defaults/pos_to_device: rint(rad2deg(pos)...
 * /canopen_driver/defaults/vel_from_device: deg2rad(obj606C)*...
 * /canopen_driver/defaults/vel_to_device: rint(rad2deg(vel)...
 * /canopen_driver/nodes: [{'name': 'joint_...
 * /canopen_driver/sync/interval_ms: 10
 * /canopen_driver/sync/overflow: 0
 * /joint_1_position_controller/joint: joint_1
 * /joint_1_position_controller/required_drive_mode: 1
 * /joint_1_position_controller/type: position_controll...
 * /joint_names: ['joint_1']
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /module_commander/publish_frequency: 10.0
 * /module_commander/use_gui: True
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /
    canopen_driver (canopen_motor_node/canopen_motor_node)
    controller_spawner (controller_manager/controller_manager)
    module_commander (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [23973]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8b0d6e5e-75f4-11e8-ac9e-78321b043645
process[rosout-1]: started with pid [23986]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [24004]
process[module_commander-3]: started with pid [24005]
process[rviz-4]: started with pid [24006]
process[canopen_driver-5]: started with pid [24018]
process[controller_spawner-6]: started with pid [24032]
[ INFO] [1529655380.689666191]: Using fixed control period: 0.010000000
[ INFO] [1529655403.644536239]: Initializing XXX
[ INFO] [1529655403.645113202]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1529655403.645543113]: Current state: 2 device error: system:0 internal_error: 0 (OK)
EMCY: 81#0000000000000000
Loaded joint_state_controller
Started ['joint_state_controller'] successfully
[controller_spawner-6] process has finished cleanly
log file: /home/akosodry/.ros/log/8b0d6e5e-75f4-11e8-ac9e-78321b043645/controller_spawner-6*.log
`

**Comment by mathias-luedtke** [comment]
Thanks!
I have now added a log outut. You should get one line or the other ;)

**Comment by akosodry** [comment]
Okeey!! Now i think something new can be reported :)

1) `roslaunch motor_control_own robot.launch` is called, nothing new happens
2) `rosservice call /driver/init` is called, and then it crashes, these are the messages:

```
success: False
message: "/home/akosodry/catkin_ws/src/ros_canopen/canopen_402/src/motor.cpp(270): Throw in\
  \ function virtual bool canopen::Motor402::isModeSupportedByDevice(uint16_t)\nDynamic\
  \ exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error>\
  \ >\nstd::exception::what: Supported drive modes (object 6502) is not valid\n; Could\
  \ not set transition"
```

And in the second window:
```
[ INFO] [1529657586.714769200]: Initializing XXX
[ INFO] [1529657586.715342315]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1529657586.715752659]: Current state: 2 device error: system:0 internal_error: 0 (OK)
EMCY: 81#0000000000000000
Supported drive modes (object 6502) is not valid
illegal tranistion 0 -> 2
[ INFO] [1529657588.831702665]: Current state: 2 device error: system:125 internal_error: 0 (OK)
[ INFO] [1529657588.831926442]: Current state: 0 device error: system:125 internal_error: 0 (OK)
[ INFO] [1529657588.832019576]: Current state: 0 device error: system:0 internal_error: 0 (OK)
[ INFO] [1529657588.832192872]: Current state: 0 device error: system:0 internal_error: 0 (OK)

```

If i change back the DataType=0x0007, then
1) `roslaunch motor_control_own robot.launch` is called, nothing new happens
2) `rosservice call /driver/init` is called, then these are the messages in the terminals:
```
success: True
message: ''
```

And in the second terminal:
```
[ INFO] [1529657824.090539323]: Initializing XXX
[ INFO] [1529657824.091134358]: Current state: 1 device error: system:0 internal_error: 0 (OK)
[ INFO] [1529657824.091600656]: Current state: 2 device error: system:0 internal_error: 0 (OK)
EMCY: 81#0000000000000000
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Supported drive modes (object 6502) not valid
Loaded joint_state_controller
Started ['joint_state_controller'] successfully
[controller_spawner-4] process has finished cleanly
log file: /home/akosodry/.ros/log/38e8f82c-75fa-11e8-ac9e-78321b043645/controller_spawner-4*.log
```

Its a bit strange, that still there are the messages: "supported drive modes not valid", but it works, the servo is turned on. 

(I double checked, the EDS file and also i run the test two times.)

**Comment by mathias-luedtke** [comment]
> Its a bit strange, that still there are the messages: "supported drive modes not valid"

My bad, I have removed "is" instead of "not" ;)
This was for debugging anyway, the crucial part is that the init service reports the error now.

Thanks for testing!
I will remove the log line and merge it.

**Pull request merged**
