### PR TITLE
Test 0.6.5 release

### PR DESCRIPTION
**Pull request by mathias-luedtke**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Seems Travis is failing ([here](https://travis-ci.org/ros-industrial/ros_canopen/jobs/168600371)):

> ```
> $ git clone https://github.com/130s/industrial_ci.git -b add/dockerbased_prerelease .ci_config
> Cloning into '.ci_config'...
> fatal: Remote branch add/dockerbased_prerelease not found in upstream origin
> ```

Are you using a custom config for `industrial_ci`, or should I report this upstream?

**Comment by mathias-luedtke** [comment]
I have used the branch of the original PR with the release feature.
However, it does not work with the upstream version either: https://travis-ci.org/ros-industrial/ros_canopen/builds/168603699

**Comment by gavanderhoorn** [comment]
@130s: any ideas?

**Comment by 130s** [comment]
2 different errors among the comments:
- https://github.com/ros-industrial/ros_canopen/pull/193#issuecomment-254528826 --> I can't reproduce this. I also mimicked this PR in my fork https://github.com/130s/ros_canopen/pull/3 but didn't occur either. The mentioned branch `add/dockerbased_prerelease` was deleted months ago when https://github.com/ros-industrial/industrial_ci/pull/35 was merged. 
  - Assuming from https://github.com/ros-industrial/ros_canopen/pull/193#issuecomment-254575036, do I not need to care this error?
- https://github.com/ros-industrial/ros_canopen/pull/193#issuecomment-254575036 I need to take a deeper look. The way to set up docker might have changed.

**Comment by mathias-luedtke** [comment]
> Assuming from #193 (comment), do I not need to care this error?

No.
The `add/dockerbased_prerelease` error was due to the old branch from testing your PR back then.
I have updated the `test-release` branch, but for some reason travis ignores the change in the PR test.

>  The way to set up docker might have changed.

Yes, something seems to be wrong with it now..

**Comment by mathias-luedtke** [comment]
https://blog.travis-ci.com/2016-09-30-the-day-we-deleted-our-vm-images/ is maybe related..

**Comment by mathias-luedtke** [comment]
@130s: https://travis-ci.org/ros-industrial/ros_canopen/jobs/168603700#L2701
I guess the script needs to be run with python3.

**Comment by 130s** [comment]
> https://travis-ci.org/ros-industrial/ros_canopen/jobs/168603700#L2701

Does line 2701 exist?
And I won't be able to work today so if it's urgent I appreciate if you could open a PR.

**Comment by 130s** [comment]
> >    https://travis-ci.org/ros-industrial/ros_canopen/jobs/168603700#L2701
> 
> Does line 2701 exist?

Now I see the error (for some reason the last time I clicked the link it only showed some 2000 lines).

> IOError: [Errno 2] No such file or directory: '/usr/lib/python2.7/dist-packages/ros_buildfarm/wrapper/apt.py'

If you could restart the build this should now be resolved.
(It's fixed in the upstream https://github.com/ros-infrastructure/ros_buildfarm/issues/347 and the patched version of a deb became available probably after your PR run.)

**Comment by mathias-luedtke** [comment]
> If you could restart the build this should now be resolved.

@130s: yea, it is resolved, thank you very much!

**Pull request merged**
